version: '3'
services:
  mongodb:
    container_name: reelreviews-mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
  app:
    container_name: reel-reviews-api
    restart: always
    build: ./
    ports:
      - '5000:5000'
    links:
      - mongodb
    environment:
      - REEL_REVIEWS_MONGODB_HOST=mongodb:27017
