version: '3'
services:
  mongodb:
    container_name: reelreviews-mongo
    restart: unless-stopped
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
    command: mongod --bind_ip 0.0.0.0
  app:
    container_name: reel-reviews-api
    restart: unless-stopped
    image: chrisgruber/reel-reviews-api
    ports:
      - '5000:5000'
    links:
      - mongodb
    environment:
      - REEL_REVIEWS_MONGODB_HOST=mongodb:27017
      - REEL_REVIEWS_ALLOW_ORIGIN=https://reelreviews.chrisgruber.com
